version: '3.8'
services:
  backend:
    build: .
    restart: always
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - mongo_db
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
  mongo_db:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
    - mongodb:/data/db
    - mongodb_config:/data/configdb
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
 mongodb:
 mongodb_config:
 db_volume:
 pgadmin-data: