"""Create table

Revision ID: 08978f455105
Revises: 44a9e8ec7a45
Create Date: 2022-08-06 19:21:55.772972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08978f455105'
down_revision = '44a9e8ec7a45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_ticket', sa.Column('date_update_status', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue_ticket', 'date_update_status')
    # ### end Alembic commands ###
